### ISSUE TITLE
Movies not synching properly

### ISSUE THREAD

**Issue by WarDrake** [speijnik/plex-watched-sync#1]
This worked great to sync my tv series, but when running it for movies, it synced 5 items out of nearly 1000 and claimed to skip the rest because they were not present on the destination server

The servers have identical data as the folders are synced while I finish setting up the move between them

source and destination on the same plex version, both running and connected to my account and on the same network
only difference is source is windwos 10 destination is Debian Buster.

**Comment by speijnik** [comment]
Hi @WarDrake,

Thank you for your feedback.

Matching is done on the individual video's "guid". For TV shows this is a URI containing the show's TVDB show ID, for movies I am unsure without having a closer look.
You might want to check if the matching of the movies is the same on the source and destination server, a mismatch would cause a skip after all.
I am open for MRs introducing different matching methods that can be selected on execution, if you want to look into this.

In any case, what this is really missing is debug information which can be printed optionally to be able to analyze situations like this one.

**Comment by WarDrake** [comment]
Thanks for the reply, I figured out the Issue, the plex scanner is no longer assigning the same type of GUID to movies as it used to before, so anything brand new, got synced, anything older than a month has different types of GUID's now 

for example, this is the same exact movie
guid="com.plexapp.agents.themoviedb://14113?lang=en"
guid="com.plexapp.agents.imdb://tt0383060?lang=en"

if I do a fix match on the original server and select the same movie, the GUID will change and will become the same as in the new server, so the program did it's job fine, the issue isn't with it

but I will probably take a look at the match method and see if I can think of something that will work and be reliable in cases like mine.

as a sidenote, adding info on how to print debug information to the readme would be helpful.
